### PR TITLE
#116  #115 Implement buttons to inform the mailman if the receiver is available to expect a delivery

### PR DESCRIPTION
**Pull request by Leililou**
Changes

1. Add  two buttons in the receivers list of message to inform his/her availability to expect a delivery
2. Change button colors for more visual
3. disable the buttons once clicked on

Issues
 #116 #115

### CODE REVIEW

**Comment by MaabMohammedali** [comment]
The mailman now can login and use the app after that he can logout and when he pressing back he didinot login again 
Great 👍 problem solved

**Comment by MaabMohammedali** [comment]
I think it is a good idea to have available and not available in receiver. When the mailman send expect message if the receiver is availbe he press on "AVALIBLE" then the mailman can send the mail.
If the reciver is not availble the mailman will not send the mail

**Review by MaabMohammedali — APPROVED** [review]

**Comment by Leililou** [comment]
Yes, I thaught also if we have the button pick up in the mailman list of messages would be easier for him/her to who comfirmed being available to pick up a delivery, he/she wont have to go back to the"notify receiver" screen o send a pick up notification, it would be accessible with the confirmatio, it is possible he/she would forget who confirmed ana who didn't

**Comment by Leililou** [comment]
Changes

Method finds the receiver by ID in the list of receivers and returns the position instead of returning a reference.
Pick up notification functional
buttons are disabled once the notification sent and stay disabled when recreate the activity

Issues
#116 #115 #122 #123 #124 #125 #126

**Comment by MaabMohammedali** [comment]
Great: I tested again I really liked that the mailman can confirm pick up fro the message , so he donot need to go back to notify receiver.After the mainlman got the messge from the receiver that he is available he can directly send "pick up " from the same screen

**Pull request merged**
