### PR TITLE
Receiver message list confirmation button

### PR DESCRIPTION
**Pull request by Leililou**
In this PR, the list of messages appear in the mailman version and the confirmation button is fuctional for the receiver, The list of meaages display the name of the sender and the message title. The confirmation button appear only when the message is "confirm pick-up" to the user and disabled once the receiver clicks on it and sends a confirmation message  to the mailman

### CODE REVIEW

**Comment by MaabMohammedali** [comment]
The app work fine .But when I login as a mailman and click on "Pick up" the receiver got two confiramtion message instead of one, I guess some thing need to fix in confirmation part.

**Comment by Leililou** [comment]
I just found and fixed the problem please check again and test

**Comment by MaabMohammedali** [comment]
I test the app again the problem is fixed  and it is work really good

**Review by MaabMohammedali — APPROVED** [review]

**Comment by Leililou** [comment]
I found another anomalie, in receiver list of messages: when you confirm pickup the buttons are disabled then when you leave the screen and reopen it the confirmed messages are again enabled

**Comment by MaabMohammedali** [comment]
We have the same isssue in mailman when he login and check messge the confirm message appear and when he log in again the same message is still there, I think when he logout everything should disaapear and for the next log in he should start from the beging after he saw the confirmation message

**Comment by Leililou** [comment]
For the mailman the message should always be there for traceability, we need to implement a date for more accuracy

**Comment by MaabMohammedali** [comment]
So for mailman we have like a history of message : good idea , so the mailman can see the rate of his work during the month or whatever

**Comment by Leililou** [comment]
Yes it's better to have the messages stored otherwise if someone complains the mailman got proof 😎

**Review by Eliflili — COMMENTED** [review]
I Reviewed the code it works

**Pull request merged**
